//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "members")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub phone: String,
    pub trust_score: Option<i32>,
    pub group_id: Option<i32>,
    pub total_contributed: Option<Decimal>,
    pub on_time_payments: Option<i32>,
    pub total_payments: Option<i32>,
    pub last_missed_payment: Option<DateTime>,
    pub status: Option<String>,
    pub joined_at: Option<DateTime>,
    pub otp_code: Option<String>,
    pub otp_expires_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::contributions::Entity")]
    Contributions,
    #[sea_orm(
        belongs_to = "super::groups::Entity",
        from = "Column::GroupId",
        to = "super::groups::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Groups,
    #[sea_orm(has_many = "super::savings_goals::Entity")]
    SavingsGoals,
    #[sea_orm(has_many = "super::transactions::Entity")]
    Transactions,
    #[sea_orm(has_many = "super::trust_score_history::Entity")]
    TrustScoreHistory,
}

impl Related<super::contributions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Contributions.def()
    }
}

impl Related<super::groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Groups.def()
    }
}

impl Related<super::savings_goals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SavingsGoals.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl Related<super::trust_score_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TrustScoreHistory.def()
    }
}
