//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod contributions;
pub mod groups;
pub mod members;
pub mod savings_deposits;
pub mod savings_goals;
pub mod transactions;
pub mod trust_score_history;
pub mod users;
