//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "savings_deposits")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub goal_id: i32,
    pub amount: Decimal,
    pub date: Option<DateTime>,
    pub moolre_ref: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::savings_goals::Entity",
        from = "Column::GoalId",
        to = "super::savings_goals::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    SavingsGoals,
}

impl Related<super::savings_goals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SavingsGoals.def()
    }
}
