//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "savings_goals")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub member_id: i32,
    pub name: String,
    pub target_amount: Decimal,
    pub current_amount: Option<Decimal>,
    pub start_date: DateTime,
    pub end_date: DateTime,
    pub frequency: String,
    pub mode: String,
    pub status: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::members::Entity",
        from = "Column::MemberId",
        to = "super::members::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Members,
    #[sea_orm(has_many = "super::savings_deposits::Entity")]
    SavingsDeposits,
}

impl Related<super::members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Members.def()
    }
}

impl Related<super::savings_deposits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SavingsDeposits.def()
    }
}
